
  services:
    mongodb:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=max
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - data:/data/db
        networks:
            - shoppinglist

    backend:
        build: ./backend
        ports:
            - 80:80
        volumes:
            - logs:/logs
            - /node_modules
        networks:
            - shoppinglist

    frontend:
        build: ./frontend
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/backend/src
        networks:
            - shoppinglist

  networks:
    shoppinglist:
        name: shoppinglist
  volumes:
      data:
      logs:
